// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AddMeetingRequest
 */
export type AddMeetingRequest = {
    /**
     * Title
     */
    title: string;
    /**
     * Date
     */
    date: string;
    /**
     * Venue
     */
    venue?: string | null;
    /**
     * Agenda
     */
    agenda?: string | null;
};

/**
 * AuthRequest
 */
export type AuthRequest = {
    /**
     * Who
     */
    who?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Batch Year
     */
    batch_year?: number | null;
};

/**
 * AuthStatusResponse
 */
export type AuthStatusResponse = {
    /**
     * Logged In
     */
    logged_in: boolean;
    /**
     * Who
     */
    who: string;
    /**
     * Id
     */
    id?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Mentor Id
     */
    mentor_id?: number | string | null;
    /**
     * Batch Year
     */
    batch_year?: number | null;
};

/**
 * BatchRequest
 */
export type BatchRequest = {
    /**
     * Batch Year
     */
    batch_year: number;
};

/**
 * BatchesResponse
 */
export type BatchesResponse = {
    /**
     * Batches
     */
    batches: Array<number>;
};

/**
 * Body_commit_students_excel_admin_commit_students_excel_post
 */
export type BodyCommitStudentsExcelAdminCommitStudentsExcelPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_commit_subjects_excel_admin_commit_subjects_excel_post
 */
export type BodyCommitSubjectsExcelAdminCommitSubjectsExcelPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_excel_excel_post
 */
export type BodyExcelExcelPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_archive_pdftoexcel_upload_post
 */
export type BodyUploadArchivePdftoexcelUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_emails_admin_upload_emails_post
 */
export type BodyUploadEmailsAdminUploadEmailsPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_mentors_admin_upload_mentors_post
 */
export type BodyUploadMentorsAdminUploadMentorsPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_note_auth_Staff_upload_notes_post
 */
export type BodyUploadNoteAuthStaffUploadNotesPost = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Path
     */
    path?: string;
};

/**
 * Body_upload_staff_list_admin_upload_staff_list_post
 */
export type BodyUploadStaffListAdminUploadStaffListPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_students_excel_admin_upload_students_excel_post
 */
export type BodyUploadStudentsExcelAdminUploadStudentsExcelPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_subjects_excel_admin_upload_subjects_excel_post
 */
export type BodyUploadSubjectsExcelAdminUploadSubjectsExcelPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_validate_students_excel_admin_validate_students_excel_post
 */
export type BodyValidateStudentsExcelAdminValidateStudentsExcelPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_validate_subjects_excel_admin_validate_subjects_excel_post
 */
export type BodyValidateSubjectsExcelAdminValidateSubjectsExcelPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ChartResponse
 */
export type ChartResponse = {
    /**
     * Image
     */
    image: string;
};

/**
 * EmailAllStatus
 */
export type EmailAllStatus = {
    /**
     * Usn
     */
    usn: string;
    /**
     * Success
     */
    success: boolean;
};

/**
 * FcmTokenRequest
 */
export type FcmTokenRequest = {
    /**
     * Fcm Token
     */
    fcm_token: string;
};

/**
 * FetchResultsRequest
 */
export type FetchResultsRequest = {
    /**
     * Usn Prefix
     */
    usn_prefix: string;
    /**
     * Usn Start
     */
    usn_start: number;
    /**
     * Usn End
     */
    usn_end: number;
    /**
     * Sem
     */
    sem: number;
    /**
     * Download Dir
     */
    download_dir?: string | null;
};

/**
 * ForgotPasswordRequest
 */
export type ForgotPasswordRequest = {
    /**
     * Username
     */
    username: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Token
     */
    token: string;
};

/**
 * MenteeActivity
 */
export type MenteeActivity = {
    /**
     * Sports
     */
    Sports?: string | null;
    /**
     * Conference Details
     */
    conference_details?: string | null;
    /**
     * Papers Published
     */
    papers_published?: string | null;
    /**
     * Certifications From Mooc
     */
    certifications_from_MOOC?: string | null;
};

/**
 * MenteeProjectInternship
 */
export type MenteeProjectInternship = {
    /**
     * Company
     */
    company?: string | null;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Duration
     */
    duration?: string | null;
    /**
     * Stipend
     */
    stipend?: string | null;
};

/**
 * MenteeSummary
 */
export type MenteeSummary = {
    /**
     * Cultural Activities
     */
    cultural_activities?: string | null;
    /**
     * Co Curricular Activities
     */
    co_curricular_activities?: string | null;
    /**
     * Hackathon
     */
    hackathon?: string | null;
    /**
     * Coding Competitions
     */
    coding_competitions?: string | null;
    /**
     * Other Achievements
     */
    other_achievements?: string | null;
};

/**
 * MenteeUploadFormRequest
 */
export type MenteeUploadFormRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Usn
     */
    usn?: string | null;
    /**
     * Mentor Name
     */
    mentor_name?: string | null;
    /**
     * Mentor Phone
     */
    mentor_phone?: string | null;
    /**
     * Temporary Address
     */
    temporary_address?: string | null;
    /**
     * Permanent Address
     */
    permanent_address?: string | null;
    /**
     * Phone Number
     */
    phone_number?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Father Name
     */
    father_name?: string | null;
    /**
     * Contact
     */
    Contact?: string | null;
    /**
     * Occupation
     */
    Occupation?: string | null;
    /**
     * Mother Name
     */
    mother_name?: string | null;
    /**
     * Contact Mother
     */
    Contact_Mother?: string | null;
    /**
     * Occupation Mother
     */
    Occupation_Mother?: string | null;
    /**
     * Sgpa
     */
    sgpa?: Array<number | string | null>;
    /**
     * Projects
     */
    projects?: Array<MenteeProjectInternship>;
    /**
     * Internships
     */
    internships?: Array<MenteeProjectInternship>;
    /**
     * Activities
     */
    activities?: Array<MenteeActivity>;
    summary?: MenteeSummary;
};

/**
 * MentorMenteeEntry
 */
export type MentorMenteeEntry = {
    /**
     * Usn
     */
    usn: string;
    /**
     * Name
     */
    name: string;
    /**
     * Parent Name
     */
    parent_name?: string | null;
    /**
     * Parent Email
     */
    parent_email?: string | null;
    /**
     * Parent Phone
     */
    parent_phone?: string | null;
};

/**
 * MentorMenteeListResponse
 */
export type MentorMenteeListResponse = {
    /**
     * Students
     */
    students: Array<MentorMenteeEntry>;
};

/**
 * MentorMessageResponse
 */
export type MentorMessageResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Subject
     */
    subject: string;
    /**
     * Message
     */
    message: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Email Failed
     */
    email_failed?: boolean;
    /**
     * Student Usn
     */
    student_usn?: string | null;
    /**
     * Read Status
     */
    read_status?: Array<MessageReadStatus>;
};

/**
 * MentorSendEmailAllRequest
 */
export type MentorSendEmailAllRequest = {
    /**
     * Recipienttype
     */
    recipientType?: string;
    /**
     * Subject
     */
    subject: string;
    /**
     * Message
     */
    message: string;
};

/**
 * MessageReadStatus
 */
export type MessageReadStatus = {
    /**
     * Usn
     */
    usn: string;
    /**
     * Name
     */
    name: string;
    /**
     * Read
     */
    read: boolean;
};

/**
 * ResetPasswordRequest
 */
export type ResetPasswordRequest = {
    /**
     * Password
     */
    password: string;
};

/**
 * SaveMessageRequest
 */
export type SaveMessageRequest = {
    /**
     * Usn
     */
    usn?: string | null;
    /**
     * Recipienttype
     */
    recipientType: string;
    /**
     * Subject
     */
    subject: string;
    /**
     * Message
     */
    message: string;
};

/**
 * SendAllEmailRequest
 */
export type SendAllEmailRequest = {
    /**
     * Recipienttype
     */
    recipientType?: 'student' | 'parent';
    /**
     * Subject
     */
    subject: string;
    /**
     * Message
     */
    message: string;
};

/**
 * SendStudentEmailRequest
 */
export type SendStudentEmailRequest = {
    /**
     * Usn
     */
    usn: string;
    /**
     * Subject
     */
    subject: string;
    /**
     * Message
     */
    message: string;
    /**
     * Recipienttype
     */
    recipientType?: 'student' | 'parent';
};

/**
 * StudentResultResponse
 */
export type StudentResultResponse = {
    /**
     * Usn
     */
    usn: string;
    /**
     * Name
     */
    name: string;
    /**
     * Sgpa
     */
    sgpa: number;
    /**
     * Cgpa
     */
    cgpa: number;
    /**
     * Percentage
     */
    percentage: number;
    /**
     * Total Marks
     */
    total_marks: number | string;
    /**
     * Credits
     */
    credits: number | string;
    /**
     * Status
     */
    status: string;
    /**
     * Subjects
     */
    subjects: Array<SubjectResult>;
    /**
     * Pdf Url
     */
    pdf_url?: string | null;
    /**
     * Semester
     */
    semester?: string | null;
};

/**
 * SubjectResult
 */
export type SubjectResult = {
    /**
     * Code
     */
    code: string;
    /**
     * Subject Name
     */
    subject_name: string;
    /**
     * Ia
     */
    ia: number | string;
    /**
     * See
     */
    see: number | string;
    /**
     * Total
     */
    total: number | string;
    /**
     * Credit
     */
    credit: number;
    /**
     * Status
     */
    status: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListBatchesBatchesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/batches';
};

export type ListBatchesBatchesGetResponses = {
    /**
     * Successful Response
     */
    200: BatchesResponse;
};

export type ListBatchesBatchesGetResponse = ListBatchesBatchesGetResponses[keyof ListBatchesBatchesGetResponses];

export type AuthAuthPostData = {
    body: AuthRequest;
    path?: never;
    query?: never;
    url: '/auth';
};

export type AuthAuthPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthAuthPostError = AuthAuthPostErrors[keyof AuthAuthPostErrors];

export type AuthAuthPostResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type AuthAuthPostResponse = AuthAuthPostResponses[keyof AuthAuthPostResponses];

export type AuthStatusAuthStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/status';
};

export type AuthStatusAuthStatusGetResponses = {
    /**
     * Successful Response
     */
    200: AuthStatusResponse;
};

export type AuthStatusAuthStatusGetResponse = AuthStatusAuthStatusGetResponses[keyof AuthStatusAuthStatusGetResponses];

export type LogoutLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type LogoutLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SaveFcmTokenStudentUsnFcmTokenPostData = {
    body: FcmTokenRequest;
    path: {
        /**
         * Usn
         */
        usn: string;
    };
    query?: never;
    url: '/student/{usn}/fcm-token';
};

export type SaveFcmTokenStudentUsnFcmTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveFcmTokenStudentUsnFcmTokenPostError = SaveFcmTokenStudentUsnFcmTokenPostErrors[keyof SaveFcmTokenStudentUsnFcmTokenPostErrors];

export type SaveFcmTokenStudentUsnFcmTokenPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthAdminHealthGetData = {
    body?: never;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/admin/health';
};

export type HealthAdminHealthGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HealthAdminHealthGetError = HealthAdminHealthGetErrors[keyof HealthAdminHealthGetErrors];

export type HealthAdminHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListBatchesAdminListBatchesGetData = {
    body?: never;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/admin/list-batches';
};

export type ListBatchesAdminListBatchesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBatchesAdminListBatchesGetError = ListBatchesAdminListBatchesGetErrors[keyof ListBatchesAdminListBatchesGetErrors];

export type ListBatchesAdminListBatchesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GenerateAccountsAdminGenerateAccountsPostData = {
    body?: never;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Mode
         */
        mode?: string;
        /**
         * Batch Year
         */
        batch_year?: number;
    };
    url: '/admin/generate-accounts';
};

export type GenerateAccountsAdminGenerateAccountsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateAccountsAdminGenerateAccountsPostError = GenerateAccountsAdminGenerateAccountsPostErrors[keyof GenerateAccountsAdminGenerateAccountsPostErrors];

export type GenerateAccountsAdminGenerateAccountsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadEmailsAdminUploadEmailsPostData = {
    body: BodyUploadEmailsAdminUploadEmailsPost;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number;
    };
    url: '/admin/upload-emails';
};

export type UploadEmailsAdminUploadEmailsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadEmailsAdminUploadEmailsPostError = UploadEmailsAdminUploadEmailsPostErrors[keyof UploadEmailsAdminUploadEmailsPostErrors];

export type UploadEmailsAdminUploadEmailsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListStaffAdminListStaffGetData = {
    body?: never;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/admin/list-staff';
};

export type ListStaffAdminListStaffGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListStaffAdminListStaffGetError = ListStaffAdminListStaffGetErrors[keyof ListStaffAdminListStaffGetErrors];

export type ListStaffAdminListStaffGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RegisterStaffAdminRegisterStaffPostData = {
    body?: never;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query: {
        /**
         * Name
         */
        name: string;
        /**
         * Email
         */
        email: string;
    };
    url: '/admin/register-staff';
};

export type RegisterStaffAdminRegisterStaffPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterStaffAdminRegisterStaffPostError = RegisterStaffAdminRegisterStaffPostErrors[keyof RegisterStaffAdminRegisterStaffPostErrors];

export type RegisterStaffAdminRegisterStaffPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadStaffListAdminUploadStaffListPostData = {
    body: BodyUploadStaffListAdminUploadStaffListPost;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/admin/upload-staff-list';
};

export type UploadStaffListAdminUploadStaffListPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadStaffListAdminUploadStaffListPostError = UploadStaffListAdminUploadStaffListPostErrors[keyof UploadStaffListAdminUploadStaffListPostErrors];

export type UploadStaffListAdminUploadStaffListPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadMentorsAdminUploadMentorsPostData = {
    body: BodyUploadMentorsAdminUploadMentorsPost;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number | null;
    };
    url: '/admin/upload-mentors';
};

export type UploadMentorsAdminUploadMentorsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadMentorsAdminUploadMentorsPostError = UploadMentorsAdminUploadMentorsPostErrors[keyof UploadMentorsAdminUploadMentorsPostErrors];

export type UploadMentorsAdminUploadMentorsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DownloadTeachersCsvAdminDownloadTeachersCsvGetData = {
    body?: never;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number;
    };
    url: '/admin/download-teachers-csv';
};

export type DownloadTeachersCsvAdminDownloadTeachersCsvGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadTeachersCsvAdminDownloadTeachersCsvGetError = DownloadTeachersCsvAdminDownloadTeachersCsvGetErrors[keyof DownloadTeachersCsvAdminDownloadTeachersCsvGetErrors];

export type DownloadTeachersCsvAdminDownloadTeachersCsvGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateBatchAdminCreateBatchPostData = {
    body: BatchRequest;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/admin/create-batch';
};

export type CreateBatchAdminCreateBatchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateBatchAdminCreateBatchPostError = CreateBatchAdminCreateBatchPostErrors[keyof CreateBatchAdminCreateBatchPostErrors];

export type CreateBatchAdminCreateBatchPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RefreshBatchAdminRefreshBatchPostData = {
    body: BatchRequest;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/admin/refresh-batch';
};

export type RefreshBatchAdminRefreshBatchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshBatchAdminRefreshBatchPostError = RefreshBatchAdminRefreshBatchPostErrors[keyof RefreshBatchAdminRefreshBatchPostErrors];

export type RefreshBatchAdminRefreshBatchPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMyAssignmentsAdminMyAssignmentsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Batch Year
         */
        batch_year: number;
    };
    url: '/admin/my-assignments';
};

export type GetMyAssignmentsAdminMyAssignmentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMyAssignmentsAdminMyAssignmentsGetError = GetMyAssignmentsAdminMyAssignmentsGetErrors[keyof GetMyAssignmentsAdminMyAssignmentsGetErrors];

export type GetMyAssignmentsAdminMyAssignmentsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type InitBatchAdminInitBatchPostData = {
    body?: never;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query: {
        /**
         * Batch Year
         */
        batch_year: number;
        /**
         * Sections
         */
        sections: Array<string>;
    };
    url: '/admin/init-batch';
};

export type InitBatchAdminInitBatchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InitBatchAdminInitBatchPostError = InitBatchAdminInitBatchPostErrors[keyof InitBatchAdminInitBatchPostErrors];

export type InitBatchAdminInitBatchPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RegisterSubjectsAdminRegisterSubjectsPostData = {
    /**
     * Subjects
     */
    body: Array<{
        [key: string]: unknown;
    }>;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query: {
        /**
         * Semester
         */
        semester: string;
    };
    url: '/admin/register-subjects';
};

export type RegisterSubjectsAdminRegisterSubjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterSubjectsAdminRegisterSubjectsPostError = RegisterSubjectsAdminRegisterSubjectsPostErrors[keyof RegisterSubjectsAdminRegisterSubjectsPostErrors];

export type RegisterSubjectsAdminRegisterSubjectsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type EnrollStudentsAdminEnrollStudentsPostData = {
    /**
     * Students
     */
    body: Array<{
        [key: string]: unknown;
    }>;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query: {
        /**
         * Batch Year
         */
        batch_year: number;
        /**
         * Section Name
         */
        section_name: string;
    };
    url: '/admin/enroll-students';
};

export type EnrollStudentsAdminEnrollStudentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EnrollStudentsAdminEnrollStudentsPostError = EnrollStudentsAdminEnrollStudentsPostErrors[keyof EnrollStudentsAdminEnrollStudentsPostErrors];

export type EnrollStudentsAdminEnrollStudentsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadSubjectsExcelAdminUploadSubjectsExcelPostData = {
    body: BodyUploadSubjectsExcelAdminUploadSubjectsExcelPost;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query: {
        /**
         * Semester
         */
        semester: string;
    };
    url: '/admin/upload-subjects-excel';
};

export type UploadSubjectsExcelAdminUploadSubjectsExcelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadSubjectsExcelAdminUploadSubjectsExcelPostError = UploadSubjectsExcelAdminUploadSubjectsExcelPostErrors[keyof UploadSubjectsExcelAdminUploadSubjectsExcelPostErrors];

export type UploadSubjectsExcelAdminUploadSubjectsExcelPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadStudentsExcelAdminUploadStudentsExcelPostData = {
    body: BodyUploadStudentsExcelAdminUploadStudentsExcelPost;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query: {
        /**
         * Batch Year
         */
        batch_year: number;
        /**
         * Section Name
         */
        section_name: string;
    };
    url: '/admin/upload-students-excel';
};

export type UploadStudentsExcelAdminUploadStudentsExcelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadStudentsExcelAdminUploadStudentsExcelPostError = UploadStudentsExcelAdminUploadStudentsExcelPostErrors[keyof UploadStudentsExcelAdminUploadStudentsExcelPostErrors];

export type UploadStudentsExcelAdminUploadStudentsExcelPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AssignSubjectsAdminAssignSubjectsPostData = {
    body?: never;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query: {
        /**
         * Teacher Username
         */
        teacher_username: string;
        /**
         * Subject Code
         */
        subject_code: string;
        /**
         * Section Id
         */
        section_id: number;
        /**
         * Semester
         */
        semester: string;
        /**
         * Batch Year
         */
        batch_year: number;
    };
    url: '/admin/assign-subjects';
};

export type AssignSubjectsAdminAssignSubjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssignSubjectsAdminAssignSubjectsPostError = AssignSubjectsAdminAssignSubjectsPostErrors[keyof AssignSubjectsAdminAssignSubjectsPostErrors];

export type AssignSubjectsAdminAssignSubjectsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListSubjectsAdminListSubjectsGetData = {
    body?: never;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/admin/list-subjects';
};

export type ListSubjectsAdminListSubjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSubjectsAdminListSubjectsGetError = ListSubjectsAdminListSubjectsGetErrors[keyof ListSubjectsAdminListSubjectsGetErrors];

export type ListSubjectsAdminListSubjectsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListSectionsAdminListSectionsGetData = {
    body?: never;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query: {
        /**
         * Batch Year
         */
        batch_year: number;
    };
    url: '/admin/list-sections';
};

export type ListSectionsAdminListSectionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSectionsAdminListSectionsGetError = ListSectionsAdminListSectionsGetErrors[keyof ListSectionsAdminListSectionsGetErrors];

export type ListSectionsAdminListSectionsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetBatchStatusAdminBatchStatusGetData = {
    body?: never;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query: {
        /**
         * Batch Year
         */
        batch_year: number;
    };
    url: '/admin/batch-status';
};

export type GetBatchStatusAdminBatchStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBatchStatusAdminBatchStatusGetError = GetBatchStatusAdminBatchStatusGetErrors[keyof GetBatchStatusAdminBatchStatusGetErrors];

export type GetBatchStatusAdminBatchStatusGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateBatchStatusAdminUpdateBatchStatusPostData = {
    body?: never;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query: {
        /**
         * Batch Year
         */
        batch_year: number;
        /**
         * Status
         */
        status: string;
    };
    url: '/admin/update-batch-status';
};

export type UpdateBatchStatusAdminUpdateBatchStatusPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateBatchStatusAdminUpdateBatchStatusPostError = UpdateBatchStatusAdminUpdateBatchStatusPostErrors[keyof UpdateBatchStatusAdminUpdateBatchStatusPostErrors];

export type UpdateBatchStatusAdminUpdateBatchStatusPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ValidateStudentsExcelAdminValidateStudentsExcelPostData = {
    body: BodyValidateStudentsExcelAdminValidateStudentsExcelPost;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query: {
        /**
         * Batch Year
         */
        batch_year: number;
    };
    url: '/admin/validate-students-excel';
};

export type ValidateStudentsExcelAdminValidateStudentsExcelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateStudentsExcelAdminValidateStudentsExcelPostError = ValidateStudentsExcelAdminValidateStudentsExcelPostErrors[keyof ValidateStudentsExcelAdminValidateStudentsExcelPostErrors];

export type ValidateStudentsExcelAdminValidateStudentsExcelPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ValidateSubjectsExcelAdminValidateSubjectsExcelPostData = {
    body: BodyValidateSubjectsExcelAdminValidateSubjectsExcelPost;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/admin/validate-subjects-excel';
};

export type ValidateSubjectsExcelAdminValidateSubjectsExcelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateSubjectsExcelAdminValidateSubjectsExcelPostError = ValidateSubjectsExcelAdminValidateSubjectsExcelPostErrors[keyof ValidateSubjectsExcelAdminValidateSubjectsExcelPostErrors];

export type ValidateSubjectsExcelAdminValidateSubjectsExcelPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CommitStudentsExcelAdminCommitStudentsExcelPostData = {
    body: BodyCommitStudentsExcelAdminCommitStudentsExcelPost;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query: {
        /**
         * Batch Year
         */
        batch_year: number;
        /**
         * Section Name
         */
        section_name: string;
    };
    url: '/admin/commit-students-excel';
};

export type CommitStudentsExcelAdminCommitStudentsExcelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CommitStudentsExcelAdminCommitStudentsExcelPostError = CommitStudentsExcelAdminCommitStudentsExcelPostErrors[keyof CommitStudentsExcelAdminCommitStudentsExcelPostErrors];

export type CommitStudentsExcelAdminCommitStudentsExcelPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CommitSubjectsExcelAdminCommitSubjectsExcelPostData = {
    body: BodyCommitSubjectsExcelAdminCommitSubjectsExcelPost;
    headers?: {
        /**
         * X-Admin-Secret
         */
        'x-admin-secret'?: string | null;
    };
    path?: never;
    query: {
        /**
         * Semester
         */
        semester: string;
    };
    url: '/admin/commit-subjects-excel';
};

export type CommitSubjectsExcelAdminCommitSubjectsExcelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CommitSubjectsExcelAdminCommitSubjectsExcelPostError = CommitSubjectsExcelAdminCommitSubjectsExcelPostErrors[keyof CommitSubjectsExcelAdminCommitSubjectsExcelPostErrors];

export type CommitSubjectsExcelAdminCommitSubjectsExcelPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExcelExcelPostData = {
    body: BodyExcelExcelPost;
    path?: never;
    query?: never;
    url: '/excel';
};

export type ExcelExcelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExcelExcelPostError = ExcelExcelPostErrors[keyof ExcelExcelPostErrors];

export type ExcelExcelPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTemplateExcelTemplateXlsxGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/excel/template.xlsx';
};

export type GetTemplateExcelTemplateXlsxGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RequestResetAuthForgotRequestPostData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/forgot/request';
};

export type RequestResetAuthForgotRequestPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestResetAuthForgotRequestPostError = RequestResetAuthForgotRequestPostErrors[keyof RequestResetAuthForgotRequestPostErrors];

export type RequestResetAuthForgotRequestPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ResetPasswordAuthForgotResetTokenPostData = {
    body: ResetPasswordRequest;
    path: {
        /**
         * Token
         */
        token: string;
    };
    query?: never;
    url: '/auth/forgot/reset/{token}';
};

export type ResetPasswordAuthForgotResetTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetPasswordAuthForgotResetTokenPostError = ResetPasswordAuthForgotResetTokenPostErrors[keyof ResetPasswordAuthForgotResetTokenPostErrors];

export type ResetPasswordAuthForgotResetTokenPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMenteeMeetingsAuthStudentMenteeMeetingStudentUsnGetData = {
    body?: never;
    path: {
        /**
         * Student Usn
         */
        student_usn: string;
    };
    query?: never;
    url: '/auth/Student/Mentee/meeting/{student_usn}';
};

export type GetMenteeMeetingsAuthStudentMenteeMeetingStudentUsnGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMenteeMeetingsAuthStudentMenteeMeetingStudentUsnGetError = GetMenteeMeetingsAuthStudentMenteeMeetingStudentUsnGetErrors[keyof GetMenteeMeetingsAuthStudentMenteeMeetingStudentUsnGetErrors];

export type GetMenteeMeetingsAuthStudentMenteeMeetingStudentUsnGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStudentMessagesStudentUsnMessagesGetData = {
    body?: never;
    path: {
        /**
         * Usn
         */
        usn: string;
    };
    query?: never;
    url: '/student/{usn}/messages';
};

export type GetStudentMessagesStudentUsnMessagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStudentMessagesStudentUsnMessagesGetError = GetStudentMessagesStudentUsnMessagesGetErrors[keyof GetStudentMessagesStudentUsnMessagesGetErrors];

export type GetStudentMessagesStudentUsnMessagesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStudentMessageDetailStudentUsnMessagesMsgIdGetData = {
    body?: never;
    path: {
        /**
         * Usn
         */
        usn: string;
        /**
         * Msg Id
         */
        msg_id: number;
    };
    query?: never;
    url: '/student/{usn}/messages/{msg_id}';
};

export type GetStudentMessageDetailStudentUsnMessagesMsgIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStudentMessageDetailStudentUsnMessagesMsgIdGetError = GetStudentMessageDetailStudentUsnMessagesMsgIdGetErrors[keyof GetStudentMessageDetailStudentUsnMessagesMsgIdGetErrors];

export type GetStudentMessageDetailStudentUsnMessagesMsgIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MarkMessageReadStudentUsnMessagesMsgIdReadPostData = {
    body?: never;
    path: {
        /**
         * Usn
         */
        usn: string;
        /**
         * Msg Id
         */
        msg_id: number;
    };
    query?: never;
    url: '/student/{usn}/messages/{msg_id}/read';
};

export type MarkMessageReadStudentUsnMessagesMsgIdReadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarkMessageReadStudentUsnMessagesMsgIdReadPostError = MarkMessageReadStudentUsnMessagesMsgIdReadPostErrors[keyof MarkMessageReadStudentUsnMessagesMsgIdReadPostErrors];

export type MarkMessageReadStudentUsnMessagesMsgIdReadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadFormMenteeUploadFormPostData = {
    body: MenteeUploadFormRequest;
    path?: never;
    query?: never;
    url: '/mentee/upload_form';
};

export type UploadFormMenteeUploadFormPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFormMenteeUploadFormPostError = UploadFormMenteeUploadFormPostErrors[keyof UploadFormMenteeUploadFormPostErrors];

export type UploadFormMenteeUploadFormPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FilesMenteeFilesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/mentee/files';
};

export type FilesMenteeFilesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DownloadMenteeDownloadFilenameGetData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/mentee/download/{filename}';
};

export type DownloadMenteeDownloadFilenameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadMenteeDownloadFilenameGetError = DownloadMenteeDownloadFilenameGetErrors[keyof DownloadMenteeDownloadFilenameGetErrors];

export type DownloadMenteeDownloadFilenameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListMentorPdfsMenteeMentorMentorIdPdfsGetData = {
    body?: never;
    path: {
        /**
         * Mentor Id
         */
        mentor_id: number;
    };
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number | null;
    };
    url: '/mentee/mentor/{mentor_id}/pdfs';
};

export type ListMentorPdfsMenteeMentorMentorIdPdfsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMentorPdfsMenteeMentorMentorIdPdfsGetError = ListMentorPdfsMenteeMentorMentorIdPdfsGetErrors[keyof ListMentorPdfsMenteeMentorMentorIdPdfsGetErrors];

export type ListMentorPdfsMenteeMentorMentorIdPdfsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DownloadMenteePdfMenteeMentorMentorIdDownloadUsnGetData = {
    body?: never;
    path: {
        /**
         * Mentor Id
         */
        mentor_id: number;
        /**
         * Usn
         */
        usn: string;
    };
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number | null;
    };
    url: '/mentee/mentor/{mentor_id}/download/{usn}';
};

export type DownloadMenteePdfMenteeMentorMentorIdDownloadUsnGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadMenteePdfMenteeMentorMentorIdDownloadUsnGetError = DownloadMenteePdfMenteeMentorMentorIdDownloadUsnGetErrors[keyof DownloadMenteePdfMenteeMentorMentorIdDownloadUsnGetErrors];

export type DownloadMenteePdfMenteeMentorMentorIdDownloadUsnGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMeetingsAuthStaffMentorMeetingMentorIdGetData = {
    body?: never;
    path: {
        /**
         * Mentor Id
         */
        mentor_id: number;
    };
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number | null;
    };
    url: '/auth/Staff/Mentor/meeting/{mentor_id}';
};

export type GetMeetingsAuthStaffMentorMeetingMentorIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMeetingsAuthStaffMentorMeetingMentorIdGetError = GetMeetingsAuthStaffMentorMeetingMentorIdGetErrors[keyof GetMeetingsAuthStaffMentorMeetingMentorIdGetErrors];

export type GetMeetingsAuthStaffMentorMeetingMentorIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddMeetingAuthStaffMentorMeetingMentorIdPostData = {
    body: AddMeetingRequest;
    path: {
        /**
         * Mentor Id
         */
        mentor_id: number;
    };
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number | null;
    };
    url: '/auth/Staff/Mentor/meeting/{mentor_id}';
};

export type AddMeetingAuthStaffMentorMeetingMentorIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddMeetingAuthStaffMentorMeetingMentorIdPostError = AddMeetingAuthStaffMentorMeetingMentorIdPostErrors[keyof AddMeetingAuthStaffMentorMeetingMentorIdPostErrors];

export type AddMeetingAuthStaffMentorMeetingMentorIdPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type DeleteMeetingAuthStaffMentorMeetingDeleteMeetingIdDeleteData = {
    body?: never;
    path: {
        /**
         * Meeting Id
         */
        meeting_id: number;
    };
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number | null;
    };
    url: '/auth/Staff/Mentor/meeting/delete/{meeting_id}';
};

export type DeleteMeetingAuthStaffMentorMeetingDeleteMeetingIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMeetingAuthStaffMentorMeetingDeleteMeetingIdDeleteError = DeleteMeetingAuthStaffMentorMeetingDeleteMeetingIdDeleteErrors[keyof DeleteMeetingAuthStaffMentorMeetingDeleteMeetingIdDeleteErrors];

export type DeleteMeetingAuthStaffMentorMeetingDeleteMeetingIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteMessageMentorMentorIdMessagesMsgIdDeleteData = {
    body?: never;
    path: {
        /**
         * Mentor Id
         */
        mentor_id: number;
        /**
         * Msg Id
         */
        msg_id: number;
    };
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number | null;
    };
    url: '/mentor/{mentor_id}/messages/{msg_id}';
};

export type DeleteMessageMentorMentorIdMessagesMsgIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMessageMentorMentorIdMessagesMsgIdDeleteError = DeleteMessageMentorMentorIdMessagesMsgIdDeleteErrors[keyof DeleteMessageMentorMentorIdMessagesMsgIdDeleteErrors];

export type DeleteMessageMentorMentorIdMessagesMsgIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMentorStudentsMentorMentorIdStudentsGetData = {
    body?: never;
    path: {
        /**
         * Mentor Id
         */
        mentor_id: number;
    };
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number | null;
    };
    url: '/mentor/{mentor_id}/students';
};

export type GetMentorStudentsMentorMentorIdStudentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMentorStudentsMentorMentorIdStudentsGetError = GetMentorStudentsMentorMentorIdStudentsGetErrors[keyof GetMentorStudentsMentorMentorIdStudentsGetErrors];

export type GetMentorStudentsMentorMentorIdStudentsGetResponses = {
    /**
     * Successful Response
     */
    200: MentorMenteeListResponse;
};

export type GetMentorStudentsMentorMentorIdStudentsGetResponse = GetMentorStudentsMentorMentorIdStudentsGetResponses[keyof GetMentorStudentsMentorMentorIdStudentsGetResponses];

export type GetMessagesMentorMentorIdMessagesGetData = {
    body?: never;
    path: {
        /**
         * Mentor Id
         */
        mentor_id: number;
    };
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number | null;
    };
    url: '/mentor/{mentor_id}/messages';
};

export type GetMessagesMentorMentorIdMessagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMessagesMentorMentorIdMessagesGetError = GetMessagesMentorMentorIdMessagesGetErrors[keyof GetMessagesMentorMentorIdMessagesGetErrors];

export type GetMessagesMentorMentorIdMessagesGetResponses = {
    /**
     * Response Get Messages Mentor  Mentor Id  Messages Get
     *
     * Successful Response
     */
    200: Array<MentorMessageResponse>;
};

export type GetMessagesMentorMentorIdMessagesGetResponse = GetMessagesMentorMentorIdMessagesGetResponses[keyof GetMessagesMentorMentorIdMessagesGetResponses];

export type SendMentorMessageMentorMentorIdMessagesPostData = {
    body: SaveMessageRequest;
    path: {
        /**
         * Mentor Id
         */
        mentor_id: number;
    };
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number | null;
    };
    url: '/mentor/{mentor_id}/messages';
};

export type SendMentorMessageMentorMentorIdMessagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendMentorMessageMentorMentorIdMessagesPostError = SendMentorMessageMentorMentorIdMessagesPostErrors[keyof SendMentorMessageMentorMentorIdMessagesPostErrors];

export type SendMentorMessageMentorMentorIdMessagesPostResponses = {
    /**
     * Successful Response
     */
    200: MentorMessageResponse;
};

export type SendMentorMessageMentorMentorIdMessagesPostResponse = SendMentorMessageMentorMentorIdMessagesPostResponses[keyof SendMentorMessageMentorMentorIdMessagesPostResponses];

export type SendEmailStudentMentorMentorIdSendEmailStudentPostData = {
    body: SendStudentEmailRequest;
    path: {
        /**
         * Mentor Id
         */
        mentor_id: number;
    };
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number | null;
    };
    url: '/mentor/{mentor_id}/send-email/student';
};

export type SendEmailStudentMentorMentorIdSendEmailStudentPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendEmailStudentMentorMentorIdSendEmailStudentPostError = SendEmailStudentMentorMentorIdSendEmailStudentPostErrors[keyof SendEmailStudentMentorMentorIdSendEmailStudentPostErrors];

export type SendEmailStudentMentorMentorIdSendEmailStudentPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SendEmailAllMentorMentorIdSendEmailAllPostData = {
    body: MentorSendEmailAllRequest;
    path: {
        /**
         * Mentor Id
         */
        mentor_id: number;
    };
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number | null;
    };
    url: '/mentor/{mentor_id}/send-email/all';
};

export type SendEmailAllMentorMentorIdSendEmailAllPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendEmailAllMentorMentorIdSendEmailAllPostError = SendEmailAllMentorMentorIdSendEmailAllPostErrors[keyof SendEmailAllMentorMentorIdSendEmailAllPostErrors];

export type SendEmailAllMentorMentorIdSendEmailAllPostResponses = {
    /**
     * Response Send Email All Mentor  Mentor Id  Send Email All Post
     *
     * Successful Response
     */
    200: Array<EmailAllStatus>;
};

export type SendEmailAllMentorMentorIdSendEmailAllPostResponse = SendEmailAllMentorMentorIdSendEmailAllPostResponses[keyof SendEmailAllMentorMentorIdSendEmailAllPostResponses];

export type GetMentorStudentsAuthStaffMentorResultGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Mentor Id
         */
        mentor_id?: number;
        /**
         * Semester
         */
        semester?: string;
        /**
         * Batch Year
         */
        batch_year?: number | null;
    };
    url: '/auth/Staff/Mentor/result';
};

export type GetMentorStudentsAuthStaffMentorResultGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMentorStudentsAuthStaffMentorResultGetError = GetMentorStudentsAuthStaffMentorResultGetErrors[keyof GetMentorStudentsAuthStaffMentorResultGetErrors];

export type GetMentorStudentsAuthStaffMentorResultGetResponses = {
    /**
     * Response Get Mentor Students Auth Staff Mentor Result Get
     *
     * Successful Response
     */
    200: Array<StudentResultResponse>;
};

export type GetMentorStudentsAuthStaffMentorResultGetResponse = GetMentorStudentsAuthStaffMentorResultGetResponses[keyof GetMentorStudentsAuthStaffMentorResultGetResponses];

export type DownloadMenteeReportAuthStaffMentorReportFilenameGetData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/auth/Staff/Mentor/report/{filename}';
};

export type DownloadMenteeReportAuthStaffMentorReportFilenameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadMenteeReportAuthStaffMentorReportFilenameGetError = DownloadMenteeReportAuthStaffMentorReportFilenameGetErrors[keyof DownloadMenteeReportAuthStaffMentorReportFilenameGetErrors];

export type DownloadMenteeReportAuthStaffMentorReportFilenameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMenteeChartAuthStaffMentorChartGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Usn
         */
        usn?: string;
        /**
         * Semester
         */
        semester?: string;
        /**
         * Batch Year
         */
        batch_year?: number | null;
    };
    url: '/auth/Staff/Mentor/chart';
};

export type GetMenteeChartAuthStaffMentorChartGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMenteeChartAuthStaffMentorChartGetError = GetMenteeChartAuthStaffMentorChartGetErrors[keyof GetMenteeChartAuthStaffMentorChartGetErrors];

export type GetMenteeChartAuthStaffMentorChartGetResponses = {
    /**
     * Successful Response
     */
    200: ChartResponse;
};

export type GetMenteeChartAuthStaffMentorChartGetResponse = GetMenteeChartAuthStaffMentorChartGetResponses[keyof GetMenteeChartAuthStaffMentorChartGetResponses];

export type GetStudentDetailsParentStudentDetailsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/parent/student-details';
};

export type GetStudentDetailsParentStudentDetailsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadArchivePdftoexcelUploadPostData = {
    body: BodyUploadArchivePdftoexcelUploadPost;
    path?: never;
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number | null;
    };
    url: '/pdftoexcel/upload';
};

export type UploadArchivePdftoexcelUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadArchivePdftoexcelUploadPostError = UploadArchivePdftoexcelUploadPostErrors[keyof UploadArchivePdftoexcelUploadPostErrors];

export type UploadArchivePdftoexcelUploadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStatusPdftoexcelStatusJobIdGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number | null;
    };
    url: '/pdftoexcel/status/{job_id}';
};

export type GetStatusPdftoexcelStatusJobIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStatusPdftoexcelStatusJobIdGetError = GetStatusPdftoexcelStatusJobIdGetErrors[keyof GetStatusPdftoexcelStatusJobIdGetErrors];

export type GetStatusPdftoexcelStatusJobIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FetchResultsRouteWebscrapeFetchResultsPostData = {
    body: FetchResultsRequest;
    path?: never;
    query?: never;
    url: '/webscrape/fetch-results';
};

export type FetchResultsRouteWebscrapeFetchResultsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FetchResultsRouteWebscrapeFetchResultsPostError = FetchResultsRouteWebscrapeFetchResultsPostErrors[keyof FetchResultsRouteWebscrapeFetchResultsPostErrors];

export type FetchResultsRouteWebscrapeFetchResultsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SendEmailToAllSendEmailAllPostData = {
    body: SendAllEmailRequest;
    path?: never;
    query?: never;
    url: '/send-email/all';
};

export type SendEmailToAllSendEmailAllPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendEmailToAllSendEmailAllPostError = SendEmailToAllSendEmailAllPostErrors[keyof SendEmailToAllSendEmailAllPostErrors];

export type SendEmailToAllSendEmailAllPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type SendEmailToStudentSendEmailStudentPostData = {
    body: SendStudentEmailRequest;
    path?: never;
    query?: never;
    url: '/send-email/student';
};

export type SendEmailToStudentSendEmailStudentPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendEmailToStudentSendEmailStudentPostError = SendEmailToStudentSendEmailStudentPostErrors[keyof SendEmailToStudentSendEmailStudentPostErrors];

export type SendEmailToStudentSendEmailStudentPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type GetMessagesMessagesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/messages';
};

export type GetMessagesMessagesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SaveMessageMessagesPostData = {
    body: SaveMessageRequest;
    path?: never;
    query?: never;
    url: '/messages';
};

export type SaveMessageMessagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveMessageMessagesPostError = SaveMessageMessagesPostErrors[keyof SaveMessageMessagesPostErrors];

export type SaveMessageMessagesPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type DeleteMessageMessagesMsgIdDeleteData = {
    body?: never;
    path: {
        /**
         * Msg Id
         */
        msg_id: number;
    };
    query?: never;
    url: '/messages/{msg_id}';
};

export type DeleteMessageMessagesMsgIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMessageMessagesMsgIdDeleteError = DeleteMessageMessagesMsgIdDeleteErrors[keyof DeleteMessageMessagesMsgIdDeleteErrors];

export type DeleteMessageMessagesMsgIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSemesterResultsAuthStaffSemResGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Semester
         */
        semester?: string;
        /**
         * Batch Year
         */
        batch_year?: number | null;
        /**
         * Section
         */
        section?: string;
    };
    url: '/auth/Staff/sem_res';
};

export type GetSemesterResultsAuthStaffSemResGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSemesterResultsAuthStaffSemResGetError = GetSemesterResultsAuthStaffSemResGetErrors[keyof GetSemesterResultsAuthStaffSemResGetErrors];

export type GetSemesterResultsAuthStaffSemResGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DownloadSemesterReportAuthStaffSemResReportSemesterGetData = {
    body?: never;
    path: {
        /**
         * Semester
         */
        semester: string;
    };
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number | null;
    };
    url: '/auth/Staff/sem_res/report/{semester}';
};

export type DownloadSemesterReportAuthStaffSemResReportSemesterGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadSemesterReportAuthStaffSemResReportSemesterGetError = DownloadSemesterReportAuthStaffSemResReportSemesterGetErrors[keyof DownloadSemesterReportAuthStaffSemResReportSemesterGetErrors];

export type DownloadSemesterReportAuthStaffSemResReportSemesterGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStudentInfoAuthStudentResultGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Usn
         */
        usn?: string;
        /**
         * Semester
         */
        semester?: string;
    };
    url: '/auth/Student/result';
};

export type GetStudentInfoAuthStudentResultGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStudentInfoAuthStudentResultGetError = GetStudentInfoAuthStudentResultGetErrors[keyof GetStudentInfoAuthStudentResultGetErrors];

export type GetStudentInfoAuthStudentResultGetResponses = {
    /**
     * Successful Response
     */
    200: StudentResultResponse;
};

export type GetStudentInfoAuthStudentResultGetResponse = GetStudentInfoAuthStudentResultGetResponses[keyof GetStudentInfoAuthStudentResultGetResponses];

export type DownloadReportAuthStudentReportFilenameGetData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/auth/Student/report/{filename}';
};

export type DownloadReportAuthStudentReportFilenameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadReportAuthStudentReportFilenameGetError = DownloadReportAuthStudentReportFilenameGetErrors[keyof DownloadReportAuthStudentReportFilenameGetErrors];

export type DownloadReportAuthStudentReportFilenameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStudentChartAuthStudentChartGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Usn
         */
        usn?: string;
        /**
         * Semester
         */
        semester?: string;
    };
    url: '/auth/Student/chart';
};

export type GetStudentChartAuthStudentChartGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStudentChartAuthStudentChartGetError = GetStudentChartAuthStudentChartGetErrors[keyof GetStudentChartAuthStudentChartGetErrors];

export type GetStudentChartAuthStudentChartGetResponses = {
    /**
     * Successful Response
     */
    200: ChartResponse;
};

export type GetStudentChartAuthStudentChartGetResponse = GetStudentChartAuthStudentChartGetResponses[keyof GetStudentChartAuthStudentChartGetResponses];

export type GetSubjectResultsAuthStaffSubResGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Semester
         */
        semester?: string;
        /**
         * Subject
         */
        subject?: string;
        /**
         * Batch Year
         */
        batch_year?: number | null;
        /**
         * Section
         */
        section?: string;
    };
    url: '/auth/Staff/sub_res';
};

export type GetSubjectResultsAuthStaffSubResGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSubjectResultsAuthStaffSubResGetError = GetSubjectResultsAuthStaffSubResGetErrors[keyof GetSubjectResultsAuthStaffSubResGetErrors];

export type GetSubjectResultsAuthStaffSubResGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSubjectReportPdfAuthStaffSubResReportGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Semester
         */
        semester?: string;
        /**
         * Subject
         */
        subject?: string;
        /**
         * Batch Year
         */
        batch_year?: number | null;
        /**
         * Section
         */
        section?: string;
    };
    url: '/auth/Staff/sub_res/report';
};

export type GetSubjectReportPdfAuthStaffSubResReportGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSubjectReportPdfAuthStaffSubResReportGetError = GetSubjectReportPdfAuthStaffSubResReportGetErrors[keyof GetSubjectReportPdfAuthStaffSubResReportGetErrors];

export type GetSubjectReportPdfAuthStaffSubResReportGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAcademicPerformanceAuthStaffOverallResGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Semester
         */
        semester?: string | null;
        /**
         * Show Toppers
         */
        show_toppers?: boolean;
        /**
         * Show Failed
         */
        show_failed?: boolean;
        /**
         * Format
         */
        format?: string;
        /**
         * Batch Year
         */
        batch_year?: number | null;
        /**
         * Section
         */
        section?: string | null;
    };
    url: '/auth/Staff/overall_res';
};

export type GetAcademicPerformanceAuthStaffOverallResGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAcademicPerformanceAuthStaffOverallResGetError = GetAcademicPerformanceAuthStaffOverallResGetErrors[keyof GetAcademicPerformanceAuthStaffOverallResGetErrors];

export type GetAcademicPerformanceAuthStaffOverallResGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetReportAuthStaffReportSemesterGetData = {
    body?: never;
    path: {
        /**
         * Semester
         */
        semester: string;
    };
    query?: {
        /**
         * Batch Year
         */
        batch_year?: number | null;
        /**
         * Section
         */
        section?: string | null;
    };
    url: '/auth/Staff/report/{semester}';
};

export type GetReportAuthStaffReportSemesterGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReportAuthStaffReportSemesterGetError = GetReportAuthStaffReportSemesterGetErrors[keyof GetReportAuthStaffReportSemesterGetErrors];

export type GetReportAuthStaffReportSemesterGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AiSummaryAiSummaryGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Usn
         */
        usn?: string;
        /**
         * Lng
         */
        lng?: string;
    };
    url: '/ai/summary';
};

export type AiSummaryAiSummaryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiSummaryAiSummaryGetError = AiSummaryAiSummaryGetErrors[keyof AiSummaryAiSummaryGetErrors];

export type AiSummaryAiSummaryGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AiTrendAiTrendGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Usn
         */
        usn?: string;
    };
    url: '/ai/trend';
};

export type AiTrendAiTrendGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiTrendAiTrendGetError = AiTrendAiTrendGetErrors[keyof AiTrendAiTrendGetErrors];

export type AiTrendAiTrendGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AiPredictCgpaAiPredictCgpaGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Usn
         */
        usn?: string;
    };
    url: '/ai/predict_cgpa';
};

export type AiPredictCgpaAiPredictCgpaGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiPredictCgpaAiPredictCgpaGetError = AiPredictCgpaAiPredictCgpaGetErrors[keyof AiPredictCgpaAiPredictCgpaGetErrors];

export type AiPredictCgpaAiPredictCgpaGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AiProfileAiProfileGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Usn
         */
        usn?: string;
        /**
         * Lng
         */
        lng?: string;
    };
    url: '/ai/profile';
};

export type AiProfileAiProfileGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiProfileAiProfileGetError = AiProfileAiProfileGetErrors[keyof AiProfileAiProfileGetErrors];

export type AiProfileAiProfileGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStudentAnalysisAuthStudentAnalysisGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Usn
         */
        usn?: string;
        /**
         * Semester
         */
        semester?: string;
    };
    url: '/auth/Student/analysis';
};

export type GetStudentAnalysisAuthStudentAnalysisGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStudentAnalysisAuthStudentAnalysisGetError = GetStudentAnalysisAuthStudentAnalysisGetErrors[keyof GetStudentAnalysisAuthStudentAnalysisGetErrors];

export type GetStudentAnalysisAuthStudentAnalysisGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListNotesAuthStudentNotesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Batch
         */
        batch?: string | null;
        /**
         * Path
         */
        path?: string;
    };
    url: '/auth/Student/notes';
};

export type ListNotesAuthStudentNotesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListNotesAuthStudentNotesGetError = ListNotesAuthStudentNotesGetErrors[keyof ListNotesAuthStudentNotesGetErrors];

export type ListNotesAuthStudentNotesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetNoteAuthStudentNotesFilePathGetData = {
    body?: never;
    path: {
        /**
         * File Path
         */
        file_path: string;
    };
    query?: never;
    url: '/auth/Student/notes/{file_path}';
};

export type GetNoteAuthStudentNotesFilePathGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetNoteAuthStudentNotesFilePathGetError = GetNoteAuthStudentNotesFilePathGetErrors[keyof GetNoteAuthStudentNotesFilePathGetErrors];

export type GetNoteAuthStudentNotesFilePathGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListNotesAuthStaffUploadNotesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path
         */
        path?: string;
    };
    url: '/auth/Staff/upload_notes';
};

export type ListNotesAuthStaffUploadNotesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListNotesAuthStaffUploadNotesGetError = ListNotesAuthStaffUploadNotesGetErrors[keyof ListNotesAuthStaffUploadNotesGetErrors];

export type ListNotesAuthStaffUploadNotesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadNoteAuthStaffUploadNotesPostData = {
    body: BodyUploadNoteAuthStaffUploadNotesPost;
    path?: never;
    query?: never;
    url: '/auth/Staff/upload_notes';
};

export type UploadNoteAuthStaffUploadNotesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadNoteAuthStaffUploadNotesPostError = UploadNoteAuthStaffUploadNotesPostErrors[keyof UploadNoteAuthStaffUploadNotesPostErrors];

export type UploadNoteAuthStaffUploadNotesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
