"""Add ExportCache table

Revision ID: 2e48107d3fcb
Revises: 5693fae5f393
Create Date: 2026-03-12 00:19:05.366153

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e48107d3fcb"
down_revision = "5693fae5f393"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "export_cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("batch_year", sa.Integer(), nullable=False),
        sa.Column("csv_content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_year"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usn", sa.String(length=50), nullable=True),
        sa.Column("recipient_type", sa.String(length=20), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("teachers", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["username"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teachers", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    op.drop_table("messages")
    op.drop_table("export_cache")
    # ### end Alembic commands ###
