"""initial migration

Revision ID: 5693fae5f393
Revises:
Create Date: 2025-10-28 23:54:04.171281

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5693fae5f393"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "processed_files", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("excel_url", sa.String(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    for table_to_drop in ["sem2_2023", "sem2_2022", "sem3_2022", "sem3_2023", "sem1_2023", "sem4_2022", "sem4_2023", "sem1_2022"]:
        if table_to_drop in existing_tables:
            op.drop_table(table_to_drop)
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["username"])

    with op.batch_alter_table("teachers", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["username"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teachers", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    op.create_table(
        "sem1_2022",
        sa.Column("student_usn", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("student_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "BMATS101_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BMATS101_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BMATS101_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BMATS101_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BCHES102_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BCHES102_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BCHES102_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCHES102_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BCEDK103_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BCEDK103_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BCEDK103_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCEDK103_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BENGK106_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BENGK106_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BENGK106_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BENGK106_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BICOK107_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BICOK107_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BICOK107_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BICOK107_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BIDTK158_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BIDTK158_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BIDTK158_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BIDTK158_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BESCK104A_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BESCK104A_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BESCK104A_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BESCK104A_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BETCK105H_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BETCK105H_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BETCK105H_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BETCK105H_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "TOTAL MARKS_Total Result", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "TOTAL MARKS_Total failed subjects",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "TOTAL MARKS_PERCENTAGE", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "TOTAL MARKS_Admission Quota", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "TOTAL MARKS_Category", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("TOTAL MARKS_Gender", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "sem4_2023",
        sa.Column("student_usn", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("student_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("BBOC407_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BBOC407_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BBOC407_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS401_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS401_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS401_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS402_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS402_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS402_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS403_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS403_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS403_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS405B_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS405B_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS405B_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BCSL305_INTERNALS",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "BCSL305_EXTERNALS",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "BCSL305_CREDITS",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("BCSL404_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCSL404_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCSL404_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BCSL456D_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BCSL456D_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BCSL456D_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BUHK408_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BUHK408_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BUHK408_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "sem4_2022",
        sa.Column("student_usn", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("student_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("BCS401_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS401_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS401_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS401_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS402_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS402_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS402_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS402_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS403_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS403_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS403_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS403_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCSL404_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCSL404_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCSL404_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCSL404_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BBOC407_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BBOC407_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BBOC407_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BBOC407_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BUHK408_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BUHK408_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BUHK408_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BUHK408_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BPEK459_PhysicalEducation_OR_BNSK459_NSS_INTERNALS",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "BPEK459_PhysicalEducation_OR_BNSK459_NSS_EXTERNALS",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "BPEK459_PhysicalEducation_OR_BNSK459_NSS_TOTAL",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "BPEK459_PhysicalEducation_OR_BNSK459_NSS_CREDITS",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("BCS405B_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS405B_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS405B_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS405B_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BCSL456D_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BCSL456D_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BCSL456D_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCSL456D_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "TOTAL Marks_Unnamed: 39_level_1",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "TOTAL Marks_TOTAL failed subjects",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "TOTAL Marks_PERCENTAGE", sa.BIGINT(), autoincrement=False, nullable=True
        ),
    )
    op.create_table(
        "sem1_2023",
        sa.Column("student_usn", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("student_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "BCEDK103_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BCEDK103_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BCEDK103_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BCHES102_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BCHES102_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BCHES102_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BENGK106_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BENGK106_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BENGK106_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BICOK107_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BICOK107_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BICOK107_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BIDTK158_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BIDTK158_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BIDTK158_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BMATS101_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BMATS101_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BMATS101_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BESCK104C_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BESCK104C_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BESCK104C_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BPLCK105B_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BPLCK105B_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BPLCK105B_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "sem3_2023",
        sa.Column("student_usn", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("student_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("BCS301_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS301_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS301_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS302_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS302_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS302_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS303_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS303_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS303_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS304_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS304_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS304_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS306A_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS306A_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS306A_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS358D_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS358D_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS358D_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCSL305_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCSL305_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCSL305_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BNSK359_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BNSK359_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BNSK359_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BSCK307_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BSCK307_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BSCK307_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "sem3_2022",
        sa.Column("student_usn", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("student_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("BCS301_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS301_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS301_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS301_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS302_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS302_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS302_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS302_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS303_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS303_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS303_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS303_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS304_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS304_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS304_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS304_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCSL305_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCSL305_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCSL305_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCSL305_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BSCK307_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BSCK307_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BSCK307_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BSCK307_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BNSK359_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BNSK359_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BNSK359_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BNSK359_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS306A_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS306A_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS306A_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS306A_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS358D_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS358D_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS358D_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BCS358D_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "TOTAL Marks_Unnamed: 39_level_1",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "TOTAL Marks_Total failed subjects",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "TOTAL Marks_PERCENTAGE", sa.BIGINT(), autoincrement=False, nullable=True
        ),
    )
    op.create_table(
        "sem2_2022",
        sa.Column("student_usn", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("student_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("BMAT201_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BMAT201_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BMAT201_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BMAT201_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BPHYS202_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BPHYS202_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BPHYS202_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BPHYS202_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BPOPS203_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BPOPS203_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BPOPS203_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BPOPS203_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BPWSK206_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BPWSK206_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BPWSK206_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BPWSK206_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BKSKK207_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BKSKK207_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BKSKK207_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BKSKK207_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BSFHK258_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BSFHK258_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BSFHK258_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BSFHK258_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BPLCK205B_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BPLCK205B_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BPLCK205B_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BPLCK205B_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BESCK204C_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BESCK204C_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BESCK204C_TOTAL", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("BESCK204C_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "TOTAL MARKS_Unnamed: 35_level_1",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "TOTAL MARKS_Total failed subjects",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "TOTAL MARKS_PERCENTAGE", sa.BIGINT(), autoincrement=False, nullable=True
        ),
    )
    op.create_table(
        "sem2_2023",
        sa.Column("student_usn", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("student_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "BKSKK207_INTERNALS",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "BKSKK207_EXTERNALS",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "BKSKK207_CREDITS",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "BPHYS202_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BPHYS202_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BPHYS202_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BPOPS203_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BPOPS203_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BPOPS203_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BPWSK206_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BPWSK206_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BPWSK206_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BSFHK258_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BSFHK258_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BSFHK258_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BESCK204D_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BESCK204D_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BESCK204D_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BETCK205H_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BETCK205H_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BETCK205H_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "BKBKK207_INTERNALS",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "BKBKK207_EXTERNALS",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "BKBKK207_CREDITS",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "BMATS201_INTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "BMATS201_EXTERNALS", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("BMATS201_CREDITS", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.drop_table("jobs")
    # ### end Alembic commands ###
