name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

  # Allow manual run
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Replace 'chetanuchiha16' with your HF username and 'acatrack' with your Space name if different
          git remote add hf https://chetanuchiha16:$HF_TOKEN@huggingface.co/spaces/chetanuchiha16/acatrack
          git push --force hf main
